#This is a simple program to determine your budget for the week!
print("Hello, we are going to set your budget for the week!")
print("First, I'd like to get your name.")
first_name = (input("Insert name: "))
print("Nice to meet you,", first_name + ",", "let's start working on your budget.")
print("To start, please tell us your take home monthly pay.")
monthly_pay = (int(input("Insert monthly pay: ")))
print("Thank you, now let's look at your expenses. How much do you spend a month on food?") 
food_expense = (int(input("Insert monthly food expense: ")))
print("And rent?")
rent_expense = (int(input("Insert monthly rent: ")))
print("Fuel and car expenses?")
car_expense = (int(input("Insert monthly car expenses: ")))
print("Ok! Now I'll calculate how much left over you have every week to spend on yourself!")
monthly_left_over = monthly_pay - (food_expense + rent_expense + car_expense)
print("Here is your weekly spending money,", first_name + ":", "$" + str((monthly_left_over / 4)))